### ISSUE TITLE
Не уменьшается баланс при вызове метода "pay"

### ISSUE THREAD

**Issue by YurinaQA** [YurinaQA/javaqa-project#10]
# Описание

При вызове метода "pay" не уменьшается сумма начального баланса

# Локация дефекта

Класс: "CreditAccount";
Метод: "pay"

https://github.com/YurinaQA/javaqa-project/blob/ed688f07aa7d56f07e4e9be31f821738f00b36b5/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения
> 1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA;
> 2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
> 3. Указать значение параметра "initialBalance" 8_000;
> 4. Указать значение параметра "creditLimit" 5_000;
> 5. Указать значение параметра "rate" 15;
> 6. Для объекта класса "CreditAccount" вызвать метод "pay" со значением 1_000;
> 7. Создать тест "Assertions.assertEquals" с аргументами (7_000, account.getBalance());
> 8. Запустить тест;
> 9. Ознакомиться с результатом теста.

## Ожидаемый результат: 
Тест проходит, баланс уменьшается на 1_000 и становится 7_000.
## Фактический результат: 
Тест не проходит, баланс становится равным -1_000.

## Выполнить тест
Тестовый класс: "CreditAccountTest";
Тест: "shouldDecreasedBalance"
https://github.com/YurinaQA/javaqa-project/blob/a1aaebfd021231a4b036493253d17a252820866f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L118

# Скриншоты
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/c09750b8-7a6e-4806-9158-ca48a9324586)
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/1bb28d01-6f36-46cb-b0bb-154c4d7f68d0)
> # Окружение
> * **Операционная система:** Windows 11 Домашняя
> * **IDEA:** IntelliJ IDEA 2023.3.6 (Community Edition)
> * **Java:** OpenJDK 11

**Comment by KnifeRing** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/385c5d66-d8fd-416c-be06-363c2a93f647)
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/119510e9-a389-44f8-8c2b-6c1d7f159735)
