### ISSUE TITLE
Не уменьшается баланс до кредитного лимита при вызове метода "pay"

### ISSUE THREAD

**Issue by YurinaQA** [YurinaQA/javaqa-project#11]
# Описание

При вызове метода "pay" не происходит уменьшение суммы начального баланса до кредитного лимита

# Локация дефекта

Класс: "CreditAccount";
Метод: "pay"

https://github.com/YurinaQA/javaqa-project/blob/ed688f07aa7d56f07e4e9be31f821738f00b36b5/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L40

# Шаги воспроизведения
> 1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA;
> 2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
> 3. Указать значение параметра "initialBalance" 8_000;
> 4. Указать значение параметра "creditLimit" 5_000;
> 5. Указать значение параметра "rate" 15;
> 6. Для объекта класса "CreditAccount" вызвать метод "pay" со значением 2_000;
> 7. Создать тест "Assertions.assertEquals" с аргументами (6_000, account.getBalance());
> 8. Запустить тест;
> 9. Ознакомиться с результатом теста

## Ожидаемый результат: 
Тест проходит, баланс уменьшается на 2_000 и становится 5_000
## Фактический результат: 
Тест не проходит, баланс становится равным -2_000

## Выполнить тест
Тестовый класс: "CreditAccountTest";
Тест: "shouldDecreasedBalanceToLimit"
https://github.com/YurinaQA/javaqa-project/blob/a1aaebfd021231a4b036493253d17a252820866f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L130

# Скриншоты
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/c09750b8-7a6e-4806-9158-ca48a9324586)
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/5ddb1e53-3ec9-4f8b-9202-7348b6846554)

> # Окружение
> * **Операционная система:** Windows 11 Домашняя
> * **IDEA:** IntelliJ IDEA 2023.3.6 (Community Edition)
> * **Java:** OpenJDK 11

**Comment by KnifeRing** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/f43b108f-e64d-49e4-8d55-2bb42208565d)
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/ccba17bd-d21f-4384-b71b-303b48ee7962)
