### ISSUE TITLE
Отсутствует исключение "IllegalArgumentException" на отрицательное значение кредитного лимита

### ISSUE THREAD

**Issue by YurinaQA** [YurinaQA/javaqa-project#12]
# Описание

 "CreditAccount" отсутствует исключение "IllegalArgumentException" на отрицательное значение кредитного лимита. 
  creditLimit - неотрицательное число.

# Локация дефекта
Класс: "CreditAccount";
Конструктор: "CreditAccount"

https://github.com/YurinaQA/javaqa-project/blob/ed688f07aa7d56f07e4e9be31f821738f00b36b5/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
> 1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA;
> 2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
> 3. Указать значение параметра "initialBalance" 2_000;
> 4. Указать значение параметра "creditLimit" -1_000;
> 5. Указать значение параметра "rate" 15;
> 6. Создать тест "Assertions.assertThrows";
> 7. Запустить тест;
> 8. Ознакомиться с результатом теста.

## Ожидаемый результат: 
Тест проходит, в консоль выводится сообщение: "Лимит по кредиту не может быть отрицательным, а у Вас: -1_000"
## Фактический результат: 
Тест не проходит, в консоль выводится сообщение: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown

## Выполнить тест
Тестовый класс: "CreditAccountTest";
Тест: "shouldExceptIfCreditLimitNegative"
https://github.com/YurinaQA/javaqa-project/blob/a1aaebfd021231a4b036493253d17a252820866f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L142

# Скриншоты
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/b45550d0-8590-43b8-afc5-4b0d93ea0f3a)
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/a86d6612-a253-4d5d-a699-bb25bd7742f9)

> # Окружение
> * **Операционная система:** Windows 11 Домашняя
> * **IDEA:** IntelliJ IDEA 2023.3.6 (Community Edition)
> * **Java:** OpenJDK 11

**Comment by KnifeRing** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/74e81283-602a-4b54-a8af-e158efb966f7)
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/aae58be0-57ca-4e98-a4ea-2e2f3ef39fbf)
