### ISSUE TITLE
Неверно рассчитывается долг по процентам при положительном балансе счёта

### ISSUE THREAD

**Issue by YurinaQA** [YurinaQA/javaqa-project#13]
# Описание

При положительном балансе на счёте сумма процентов на отрицательный баланс счёта должна оставаться равной нулю.
При выполнении данного теста сумма процентов на отрицательный баланс счёта посчиталась как при отрицательном балансе.

# Локация дефекта
Класс: "CreditAccount";
Метод: "yearChange"

https://github.com/YurinaQA/javaqa-project/blob/ed688f07aa7d56f07e4e9be31f821738f00b36b5/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L82

# Шаги воспроизведения
> 1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA;
> 2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
> 3. Указать значение параметра "initialBalance" 1_000;
> 4. Указать значение параметра "creditLimit" 5_000;
> 5. Указать значение параметра "rate" 15;
> 6. Создать тест "Assertions.assertEquals" с аргументами (0, account.yearChange());
> 7. Запустить тест;
> 8. Ознакомиться с результатом теста.

## Ожидаемый результат: 
Тест проходит, сумма процентов равна 0
## Фактический результат: 
Тест не проходит, сумма процентов равна -75

## Выполнить тест
Тестовый класс: "CreditAccountTest";
Тест: "debtIfBalancePositive"
https://github.com/YurinaQA/javaqa-project/blob/a1aaebfd021231a4b036493253d17a252820866f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L151

# Скриншоты
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/f2bfab81-8a88-4e12-844f-7a8a498c0d34)
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/532fb26a-5747-4e93-8b84-04408c876354)

> # Окружение
> * **Операционная система:** Windows 11 Домашняя
> * **IDEA:** IntelliJ IDEA 2023.3.6 (Community Edition)
> * **Java:** OpenJDK 11

**Comment by KnifeRing** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/7aa8994d-23ff-4e10-addc-cfb095b9275f)
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/1d0a980a-5143-41b1-b4ad-3866d0698523)
