### ISSUE TITLE
Отсутствует исключение "IllegalArgumentException" на значение кредитного лимита, равное нулю

### ISSUE THREAD

**Issue by YurinaQA** [YurinaQA/javaqa-project#14]
# Описание
У конструктора "CreditAccount" отсутствует исключение "IllegalArgumentException" на значение начального баланса, равное нулю. initialBalance не может быть равно нулю

# Локация дефекта
Класс: "CreditAccount";
Конструктор: "CreditAccount"

https://github.com/YurinaQA/javaqa-project/blob/ed688f07aa7d56f07e4e9be31f821738f00b36b5/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19

# Шаги воспроизведения
> 1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA;
> 2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
> 3. Указать значение параметра "initialBalance" 0;
> 4. Указать значение параметра "creditLimit" 1_000;
> 5. Указать значение параметра "rate" 15;
> 6. Создать тест "Assertions.assertThrows";
> 7. Запустить тест;
> 8. Ознакомиться с результатом теста

## Ожидаемый результат: 
Тест проходит, в консоль выводится сообщение: "Начальный баланс не может быть равен нулю, а у Вас: 0"
## Фактический результат: 
Тест не проходит, в консоль выводится сообщение: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown

## Выполнить тест
Тестовый класс: "CreditAccountTest";
Тест: "shouldExceptIfInitialBalanceNull"
https://github.com/YurinaQA/javaqa-project/blob/a1aaebfd021231a4b036493253d17a252820866f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L161

# Скриншоты
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/b45550d0-8590-43b8-afc5-4b0d93ea0f3a)
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/ed2690c2-ee78-4aa7-8b83-69612d4ce435)

> # Окружение
> * **Операционная система:** Windows 11 Домашняя
> * **IDEA:** IntelliJ IDEA 2023.3.6 (Community Edition)
> * **Java:** OpenJDK 11

**Comment by KnifeRing** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/32160fbc-e7b5-4e46-a9a5-87a4f8488d54)
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/70b45391-7441-4773-b389-abedec9285a1)
