### ISSUE TITLE
Отсутствует исключение "IllegalArgumentException" на отрицательное значение начального баланса

### ISSUE THREAD

**Issue by YurinaQA** [YurinaQA/javaqa-project#15]
> # Описание
 У конструктора "CreditAccount" отсутствует исключение "IllegalArgumentException" на отрицательное значение начального баланса
initialBalance - неотрицательное число
> 
> # Локация дефекта
> Класс: "CreditAccount"; Конструктор: "CreditAccount"
> 
> https://github.com/YurinaQA/javaqa-project/blob/ed688f07aa7d56f07e4e9be31f821738f00b36b5/src/main/java/ru/netology/javaqadiplom/CreditAccount.java#L19
> 
> # Шаги воспроизведения
> 1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/credit/src/main/java/ru/netology/javaqadiplom/CreditAccount.java) в IDEA;
> 2. В тестовом классе "CreditAccountTest" создать объект класса "CreditAccount";
> 3. Указать значение параметра "initialBalance" -2_000;
> 4. Указать значение параметра "creditLimit" 1_000;
> 5. Указать значение параметра "rate" 15;
> 6. Создать тест "Assertions.assertThrows";
> 7. Запустить тест;
> 8. Ознакомиться с результатом теста

 ## Ожидаемый результат:
Тест проходит, в консоль выводится сообщение: "Начальный баланс не может быть отрицательным, а у Вас: -2_000"
 ## Фактический результат:
Тест не проходит, в консоль выводится сообщение: Expected java.lang.IllegalArgumentException to be thrown, but nothing was thrown

 ## Выполнить тест
Тестовый класс: "CreditAccountTest"; 
Тест: "shouldExceptIfCreditLimitNegative2"
https://github.com/YurinaQA/javaqa-project/blob/a1aaebfd021231a4b036493253d17a252820866f/src/test/java/ru/netology/javaqadiplom/CreditAccountTest.java#L170
 
 # Скриншоты
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/8b911e5f-69be-40db-949d-6005a5987551)
 
 # Окружение
 
 * **Операционная система:** Windows 11 Домашняя
 * **IDEA:** IntelliJ IDEA 2023.3.6 (Community Edition)
 * **Java:** OpenJDK 11

**Comment by KnifeRing** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/6dd1ddb8-9488-4ee5-8247-3814f5392ef8)
