### ISSUE TITLE
Не обновляется баланс при успешном пополнении счета при вызове метода add

### ISSUE THREAD

**Issue by KnifeRing** [YurinaQA/javaqa-project#3]
# Описание
При успешном пополнении счета, при вызове метода **add** для пополнения счета, значение
баланса не увеличивается на сумму пополнения. Присваивается значение суммы пополнения. 

# Локация дефекта
https://github.com/YurinaQA/javaqa-project/blob/4f1ffcf924ec3718b2d6be5c5fa7758b051c5a7c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L72

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2.Создать объект класса SavingAccount с начальным балансом 2_000 и максимальным балансом 10_000.
3. Вызвать метод add с параметром amount равным 3_000.
4. Проверить значение баланса после выполнения метода add.

**Ожидаемый результат:** Баланс должен быть равен 5_000 (начальный баланс + сумма пополнения).
**Фактический результат:** Баланс равен 3_000, что указывает на неверное обновление баланса.

# Тест
https://github.com/YurinaQA/javaqa-project/blob/c2dd7177ed155fcc8f9ad511e0d56b4e2c329210/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L9

# Скриншот
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/49190c41-8652-4b7d-b94f-de5fd9cc4e12)

# Окружение
* **Операционная система:** Windows 10LTSC
* **IDE:** IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by YurinaQA** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/e5ce4e2f-6b15-4a08-9c40-03f9b72d79ba)
