### ISSUE TITLE
При отрицательном начальном балансе не выкидывается исключение IllegalArgumentException

### ISSUE THREAD

**Issue by KnifeRing** [YurinaQA/javaqa-project#4]
# Описание
Если начальный баланс отрицательный, должно выкидываться исключение IllegalArgumentException.
"Начальный баланс не может быть отрицательным, а у вас: "

# Локация дефекта
https://github.com/YurinaQA/javaqa-project/blob/4f1ffcf924ec3718b2d6be5c5fa7758b051c5a7c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса SavingAccount с начальным балансом -5_000, минимальным балансом 1_000, максимальным балансом 10_000 и процентной ставкой 5.
3. Запустить программу.
4. Проверить значение баланса после выполнения функции.

**Ожидаемый результат:** Выбрасывается исключение IllegalArgumentException, так как начальный баланс отрицательный.
**Фактический результат:** Исключение не выбрасывается.

# Тест
https://github.com/YurinaQA/javaqa-project/blob/ccc5cbc7597987f00f66c4ea7c448fd3db96e8ce/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L114

# Скриншот
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/3a0a8b03-59c0-43fc-8bb8-2f143d3059e6)

# Окружение
* **Операционная система:** Windows 10LTSC
* **IDE:** IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by YurinaQA** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/e64863cf-95e0-43da-b2ca-6fdc909db2aa)
