### ISSUE TITLE
При отрицательном минимальном балансе, не выкидывается исключение IllegalArgumentException

### ISSUE THREAD

**Issue by KnifeRing** [YurinaQA/javaqa-project#5]
# Описание
Если минимальный баланс отрицательный, должно выкидываться исключение IllegalArgumentException.
"Минимальный баланс не может быть отрицательным, а у вас: "

# Локация дефекта
https://github.com/YurinaQA/javaqa-project/blob/4f1ffcf924ec3718b2d6be5c5fa7758b051c5a7c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса SavingAccount с начальным балансом 2_000, минимальным балансом -1_000, максимальным балансом 10_000 и процентной ставкой 5.
3. Запустить программу.
4. Проверить значение баланса после выполнения функции.

**Ожидаемый результат:** Выбрасывается исключение IllegalArgumentException, так как минимальный баланс отрицательный.
**Фактический результат:** Исключение не выбрасывается.

# Тест
https://github.com/YurinaQA/javaqa-project/blob/558b98ccd3f2529ae79b718214ccdaf0617fd812/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L126

# Скриншот
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/a173373d-e4ad-4e0b-b641-815fb5d5e326)

# Окружение
* **Операционная система:** Windows 10LTSC
* **IDE:** IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by YurinaQA** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/4961f049-9b22-4b64-a754-6a53fa48b127)
