### ISSUE TITLE
При отрицательном максимальном балансе не выкидывается исключение IllegalArgumentException

### ISSUE THREAD

**Issue by KnifeRing** [YurinaQA/javaqa-project#6]
# Описание
Если минимальный баланс отрицательный, должно выкидываться исключение IllegalArgumentException.
"Максимальный баланс не может быть отрицательным, а у вас: "

# Локация дефекта
https://github.com/YurinaQA/javaqa-project/blob/4f1ffcf924ec3718b2d6be5c5fa7758b051c5a7c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса SavingAccount с начальным балансом 2_000, минимальным балансом 1_000, максимальным балансом -10_000 и процентной ставкой 5.
3. Запустить программу.
4. Проверить значение баланса после выполнения функции.

**Ожидаемый результат:** Выбрасывается исключение IllegalArgumentException, так как максимальный баланс отрицательный.
**Фактический результат:** Исключение не выбрасывается.

# Тест
https://github.com/YurinaQA/javaqa-project/blob/558b98ccd3f2529ae79b718214ccdaf0617fd812/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L138

# Скриншот
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/980269e8-3f9e-4a20-8923-4c58654ff887)

# Окружение
* **Операционная система:** Windows 10LTSC
* **IDE:** IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by YurinaQA** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/ba790f19-ba3b-4d37-ac51-de7151b265a0)
