### ISSUE TITLE
Не выкидывается исключение IllegalArgumentException, если максимальный баланс меньше минимального 

### ISSUE THREAD

**Issue by KnifeRing** [YurinaQA/javaqa-project#7]
# Описание
Если  максимальный баланс меньше минимального , должно выкидываться исключение IllegalArgumentException.
"Минимальный баланс не может быть выше максимального баланса, а у вас "

# Локация дефекта
https://github.com/YurinaQA/javaqa-project/blob/4f1ffcf924ec3718b2d6be5c5fa7758b051c5a7c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса SavingAccount с начальным балансом 2_000, минимальным балансом 1_000, максимальным балансом 100 и процентной ставкой 5.
3. Запустить программу.
4. Проверить значение баланса после выполнения функции.

**Ожидаемый результат:** Выбрасывается исключение IllegalArgumentException, так как минимальный баланс больше максимального.
**Фактический результат:** Исключение не выбрасывается.

# Тест
https://github.com/YurinaQA/javaqa-project/blob/558b98ccd3f2529ae79b718214ccdaf0617fd812/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L162

# Скриншот
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/deea38b1-e014-476c-a60b-4a915effc157)

# Окружение
* **Операционная система:** Windows 10LTSC
* **IDE:** IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by YurinaQA** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/2d979017-f95c-4520-86d8-88f27faa0a07)

**Comment by YurinaQA** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/a76b7a6e-3aee-47c0-bde8-791d5fde432b)
