### ISSUE TITLE
Не выкидывается исключение IllegalArgumentException, если начальный баланс меньше минимального

### ISSUE THREAD

**Issue by KnifeRing** [YurinaQA/javaqa-project#8]
# Описание
Если начальный баланс меньше минимального, должно выкидываться исключение IllegalArgumentException.
"Начальный баланс не может быть ниже минимального баланса, а у вас "

# Локация дефекта
https://github.com/YurinaQA/javaqa-project/blob/4f1ffcf924ec3718b2d6be5c5fa7758b051c5a7c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса SavingAccount с начальным балансом 200, минимальным балансом 1_000, максимальным балансом 10_000 и процентной ставкой 5.
3. Запустить программу.
4. Проверить значение баланса после выполнения функции.

**Ожидаемый результат:** Выбрасывается исключение IllegalArgumentException, так как  начальный баланс меньше минимального.
**Фактический результат:** Исключение не выбрасывается.

# Тест
https://github.com/YurinaQA/javaqa-project/blob/558b98ccd3f2529ae79b718214ccdaf0617fd812/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L175

# Скриншот
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/bf0e9686-d7dc-4760-a788-e2bf5f10f2f7)

# Окружение
* **Операционная система:** Windows 10LTSC
* **IDE:** IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by YurinaQA** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/b4551865-deb4-4daf-a77a-8a25432cdf24)
