### ISSUE TITLE
Не выкидывается исключение IllegalArgumentException, если начальный баланс больше максимального

### ISSUE THREAD

**Issue by KnifeRing** [YurinaQA/javaqa-project#9]
# Описание
Если начальный баланс больше максимального, должно выкидываться исключение IllegalArgumentException.
"Начальный баланс не может быть больше максимального баланса, а у вас "

# Локация дефекта
https://github.com/YurinaQA/javaqa-project/blob/4f1ffcf924ec3718b2d6be5c5fa7758b051c5a7c/src/main/java/ru/netology/javaqadiplom/SavingAccount.java#L22

# Шаги воспроизведения
1. Открыть [код программы](https://github.com/YurinaQA/javaqa-project/blob/main/src/main/java/ru/netology/javaqadiplom/SavingAccount.java) в IDEA.
2. Создать объект класса SavingAccount с начальным балансом 20_000, минимальным балансом 1_000, максимальным балансом 10_000 и процентной ставкой 5.
3. Запустить программу.
4. Проверить значение баланса после выполнения функции.

**Ожидаемый результат:** Выбрасывается исключение IllegalArgumentException, так как начальный баланс больше максимального.
**Фактический результат:** Исключение не выбрасывается.

# Тест
https://github.com/YurinaQA/javaqa-project/blob/558b98ccd3f2529ae79b718214ccdaf0617fd812/src/test/java/ru/netology/javaqadiplom/SavingAccountTest.java#L188

# Скриншот
![image](https://github.com/YurinaQA/javaqa-project/assets/100803386/1e04eab9-5ff0-49f1-acb2-6b5259ed0834)

# Окружение
* **Операционная система:** Windows 10LTSC
* **IDE:** IntelliJ IDEA 2023.3.6 (Ultimate Edition)
* **Java:** OpenJDK 11

**Comment by YurinaQA** [comment]
![image](https://github.com/YurinaQA/javaqa-project/assets/158807207/62461726-5dc3-4fb3-8a34-f743d24bc23e)
